server:
  port: 9999

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
#        server-addr: ${NACOS_HOST:pig-register}:${NACOS_PORT:8848}
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        watch:
          enabled: true
        watch-delay: 1000
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: cb35c8c5-4331-4105-9c20-2c04fa3fb43a
  config:
    import:
      - optional:nacos:application-@profiles.active@.yml
      - optional:nacos:${spring.application.name}-@profiles.active@.yml





