server:
  port: 4002

spring:
  application:
    name: @artifactId@  # oms-biz
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: cb35c8c5-4331-4105-9c20-2c04fa3fb43a
  config:
    import:
      - nacos:application-@profiles.active@.yml
      - nacos:${spring.application.name}-@profiles.active@.yml



mybatis-plus:
  mapper-locations: classpath*:/com.jinpus.tpms.mapper.xml/*.xml



  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB