server:
  port: 4001

spring:
  application:
    name: @artifactId@  #jinpus-tpms
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:application-@profiles.active@.yml
      - nacos:${spring.application.name}-@profiles.active@.yml



mybatis-plus:
  mapper-locations: classpath*:/com.jinpus.tpms.mapper.xml/*.xml


